spring.application.name=order-service

server.port=8081

# H2 Configuration
spring.datasource.url=jdbc:h2:mem:orderdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Show SQL logs
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true

# Kafka Configuration- for producer
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Matches the alias token defined in inventory-service
# Producer Mapping (Outgoing)
spring.kafka.producer.properties.spring.json.type.mapping=orderPlacedEvent:com.siddharth.order_service.dto.OrderPlacedEvent

# Inbound Consumer Configurations for Order Service
spring.kafka.consumer.group-id=order-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

# Delegate parsing to JSON Deserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer

# Trust and Mapping configuration for incoming responses
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.type.mapping=inventoryProcessedEvent:com.siddharth.order_service.dto.InventoryProcessedEvent


# Increase scheduler pool size so tasks don't block each other
spring.task.scheduling.pool.size=5
spring.task.scheduling.thread-name-prefix=outbox-sched-thread-

# Tracing Configuration

# Enable overall tracing
management.tracing.enabled=true
# 1.0 means sample 100% of requests (Production usually uses 0.1 / 10% to save disk space)
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans

# Crucial Spring Boot 3 property to enable tracing context propagation over Kafka
spring.kafka.template.observation-enabled=true
spring.kafka.listener.observation-enabled=true

# Expose Actuator observation endpoints
management.endpoints.web.exposure.include=health,info,metrics,prometheus

# Include Trace ID and Span ID explicitly into your local console logging layout
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]

//--------LOGGING-------
# Set the root logging level to INFO (keeps standard app logs clean)
logging.level.root=INFO

# Silence Kafka driver connection/disconnection warnings and poll noise
logging.level.org.apache.kafka=ERROR
logging.level.org.springframework.kafka=WARN

# Silence Hibernate SQL binding metadata noise (Change to DEBUG only if debugging SQL)
logging.level.org.hibernate.SQL=WARN
logging.level.org.hibernate.type.descriptor.sql=WARN

# Quiet the general background noise of Spring boot framework infrastructure
logging.level.org.springframework.web=WARN
//-------END------------